---
jobs:

- name: unit-test
  plan:
  - get: cf-sample-app-spring
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pottava/groovy
      inputs:
        - name: cf-sample-app-spring
      run:
        path: groovy
        args:
        - cf-sample-app-spring/appTest.groovy

- name: deploy-to-cf
  plan:
  - get: cf-sample-app-spring
    trigger: true
    passed: [unit-test]
  - put: deployment
    params:
      manifest: cf-sample-app-spring/manifest.yml
      path: cf-sample-app-spring/app.groovy

resources:
- name: cf-sample-app-spring
  type: git
  source:
    uri: https://github.com/avade/cf-sample-app-spring

- name: deployment
  type: cf
  source:
    api: {{cfapi}}
    username: {{cfemail}}
    password: {{cfpassword}}
    organization: {{cforg}}
    space: {{cfspace}}
    skip_cert_check: true
